// ============================================================================
// heroLqip — 히어로 사진 LQIP(사전 블러 처리한 초소형 base64 플레이스홀더)
//
// 용도: HomeHero 사진 타일의 background-image 2번째 레이어로 사용.
//   원본(home-0X.jpg)이 도착하기 전 흐릿한 플레이스홀더를 즉시(인라인, 0요청) 표시.
//   sharp로 32px 축소 + blur 후 생성(각 ~1KB). 빌드 스크립트 없이 정적 포함.
// ============================================================================

export const HERO_LQIP: Record<'01' | '02' | '03' | '04', string> = {
  '01': 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAlACADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMEBQb/xAAfEAACAgIDAQEBAAAAAAAAAAABAgADETEEEyESIlH/xAAXAQEBAQEAAAAAAAAAAAAAAAABAAID/8QAGBEBAQEBAQAAAAAAAAAAAAAAAAERAhL/2gAMAwEAAhEDEQA/AOeUFjqWU8RnX7A1FUWrgLj2b3DQCjW4FiXNcq4OcSE/2dHzKF6zgTn7K2DHyOjF3G4Z7BmbiKEQCIpUO2RKSRqcvTWwq4gqRIVrqYkEey51+gcSNqwrHO4W6Z1D63KV+RK3t2QhLliLA35zILmPbmEJQP/Z',
  '02': 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAlACADASIAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAUCBAYBA//EAB8QAAICAgIDAQAAAAAAAAAAAAABAgMEESExEiJRQf/EABcBAQEBAQAAAAAAAAAAAAAAAAABAgP/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AG9WTGS2me8b0ZjEzvF6bGteRGcd7DEpzC1Mn5Cuu74yzC76GtYKm3ZcqyZR4TFyS3wSjJvpkcT2jMlHsuQzk+GzORyGlonC+Tl2F1Rhyzr9XwAAS/dnXJroAKP/2Q==',
  '03': 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAlACADASIAAhEBAxEB/8QAGQAAAwADAAAAAAAAAAAAAAAAAAIEAQMF/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIAAxEhBBIiMRMUQf/EABgBAAMBAQAAAAAAAAAAAAAAAAECAwQA/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwBEdm/JSlnXGREUdR6j4DCY9SiqrkhjrRj/AGHJktVR7Srp1HqPLdM5NdjPLeOFQ+czxEqU7xKr6kdMjUEjpGv5aw3jKGuRkwBucwIVYzaraxKTQ1HQTnOZS1rY9whJQCCwzDEg5EITRAf/2Q==',
  '04': 'data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAlACADASIAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAABQYAAwQBAv/EACIQAAICAQQCAwEAAAAAAAAAAAECAAMRBAUSISJBExUxMv/EABgBAAMBAQAAAAAAAAAAAAAAAAECAwAE/8QAGhEBAQACAwAAAAAAAAAAAAAAAQACAxEhMf/aAAwDAQACEQMRAD8AWL05diZwCD+GNf1daL5dzg2yk+hOY2h1LLOTjuVklj1De5betS5XqCePESmOQ9wJ1exCuSRiYm1tVb/0MRdbc7vj45Mytc7nsmKarcMa3jXrYAtZgtfMTzTS1xhBNHwWMgeR4hjKJV7kkjkSLbaBiEbjhepJJN9hf//Z',
};
